#!/usr/bin/env python3
"""Build executor cases from output.csv and validate mglru_executor.py."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from mglru_project.mglru.mglru_eBPF.mglru_executor import ExecutorConfig, exec_shrink_lruvec, load_case, to_range_label


DEFAULT_RELATIVE_TOLERANCE = 0.10
DEFAULT_ZERO_ABS_TOLERANCE = 64


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate mglru_executor.py against output.csv")
    parser.add_argument(
        "--csv",
        default=str(Path(__file__).resolve().parent / "mglru_eBPF" / "output.csv"),
        help="Path to output.csv generated by mglru_monitor",
    )
    parser.add_argument(
        "--case-out",
        default=str(Path(__file__).resolve().parent / "selected_kswapd0_case.json"),
        help="Where to write the selected representative case JSON",
    )
    parser.add_argument(
        "--batch-dir",
        default=str(Path(__file__).resolve().parent / "generated_cases"),
        help="Directory to export all filtered cases as JSON",
    )
    parser.add_argument(
        "--results-csv",
        default=str(Path(__file__).resolve().parent / "executor_validation_results.csv"),
        help="Where to write per-row validation results",
    )
    parser.add_argument(
        "--summary-json",
        default=str(Path(__file__).resolve().parent / "executor_validation_summary.json"),
        help="Where to write summary metrics",
    )
    parser.add_argument(
        "--top-errors-json",
        default=str(Path(__file__).resolve().parent / "executor_top_error_cases.json"),
        help="Where to write the highest-error cases",
    )
    parser.add_argument("--max-evict-rounds", type=int, default=ExecutorConfig.max_evict_rounds)
    parser.add_argument("--min-isolate-pages", type=int, default=ExecutorConfig.min_isolate_pages)
    parser.add_argument("--relative-tolerance", type=float, default=DEFAULT_RELATIVE_TOLERANCE)
    parser.add_argument("--zero-abs-tolerance", type=int, default=DEFAULT_ZERO_ABS_TOLERANCE)
    parser.add_argument("--top-k", type=int, default=20, help="How many highest-error cases to export")
    parser.add_argument(
        "--trigger-comm",
        default="kswapd0",
        help="Only validate rows whose trigger_comm matches this value; use 'all' to disable filtering",
    )
    parser.add_argument(
        "--no-top-errors-json",
        action="store_true",
        help="Do not write the highest-error cases JSON file (default behavior)",
    )
    parser.add_argument(
        "--no-top-errors-in-summary",
        action="store_true",
        help="Do not include top_error_cases in the summary JSON or console output (default behavior)",
    )
    parser.add_argument(
        "--write-top-errors-json",
        dest="no_top_errors_json",
        action="store_false",
        help="Write the highest-error cases JSON file",
    )
    parser.add_argument(
        "--include-top-errors-in-summary",
        dest="no_top_errors_in_summary",
        action="store_false",
        help="Include top_error_cases in the summary JSON and console output",
    )
    parser.set_defaults(
        no_top_errors_json=True,
        no_top_errors_in_summary=True,
    )
    return parser.parse_args()


def as_int(row: Dict[str, str], key: str, default: int = 0) -> int:
    value = row.get(key)
    if value is None or value == "":
        return default
    return int(value)


def as_bool_from_int(row: Dict[str, str], key: str, default: bool = False) -> bool:
    return bool(as_int(row, key, int(default)))


def rebuild_gens(
    min_seq: int,
    max_seq: int,
    oldest: int,
    second_oldest: int,
    second_youngest: int,
    youngest: int,
) -> List[Dict[str, int]]:
    count = max(0, max_seq - min_seq + 1)
    if count == 0:
        return []
    if count > 4:
        raise ValueError(f"cannot rebuild {count} generations from 4-window summary")

    pages_by_offset = [0] * count
    pages_by_offset[0] = oldest
    if count >= 2:
        pages_by_offset[-1] = youngest
    if count >= 3:
        pages_by_offset[1] = second_oldest
    if count >= 4:
        pages_by_offset[-2] = second_youngest

    return [
        {"seq": min_seq + offset, "pages": int(max(pages, 0))}
        for offset, pages in enumerate(pages_by_offset)
    ]


def build_case_json(row: Dict[str, str]) -> Dict[str, Any]:
    trigger_comm = row["trigger_comm"]
    anon_min_seq = as_int(row, "anon_min_gen_seq")
    file_min_seq = as_int(row, "file_min_gen_seq")
    max_seq = as_int(row, "max_gen_seq")
    swappiness = as_int(row, "feature_swappiness")
    gfp_mask = as_int(row, "feature_gfp_mask")

    return {
        "reclaim_context": "kswapd" if trigger_comm.startswith("kswapd") else "direct reclaim",
        "trigger_comm": trigger_comm,
        "swappiness": swappiness,
        "memory_reclaim_type": "global reclaim",
        "memcg_id": as_int(row, "memcg_id"),
        "memcg_path": None,
        "node_id": 0,
        "max_seq": max_seq,
        "min_seq_anon": anon_min_seq,
        "min_seq_file": file_min_seq,
        "anon_gens": rebuild_gens(
            anon_min_seq,
            max_seq,
            as_int(row, "feature_anon_oldest_gen_pages"),
            as_int(row, "feature_anon_second_oldest_gen_pages"),
            as_int(row, "feature_anon_second_youngest_gen_pages"),
            as_int(row, "feature_anon_youngest_gen_pages"),
        ),
        "file_gens": rebuild_gens(
            file_min_seq,
            max_seq,
            as_int(row, "feature_file_oldest_gen_pages"),
            as_int(row, "feature_file_second_oldest_gen_pages"),
            as_int(row, "feature_file_second_youngest_gen_pages"),
            as_int(row, "feature_file_youngest_gen_pages"),
        ),
        "priority": as_int(row, "feature_priority"),
        "reclaim_idx": as_int(row, "feature_reclaim_idx"),
        "order": as_int(row, "feature_order"),
        "gfp_io": bool(gfp_mask),
        "gfp_mask": gfp_mask,
        "nr_to_reclaim": as_int(row, "feature_nr_to_reclaim"),
        "observed_evict_folios_calls": as_int(row, "feature_evict_folios_calls"),
        "observed_isolate_calls_anon": as_int(row, "feature_isolate_calls_anon"),
        "observed_isolate_calls_file": as_int(row, "feature_isolate_calls_file"),
        "observed_isolated_anon_pages": as_int(row, "feature_isolated_anon_pages"),
        "observed_isolated_file_pages": as_int(row, "feature_isolated_file_pages"),
        "observed_after_min_seq_anon": as_int(row, "feature_after_anon_min_gen_seq"),
        "observed_after_min_seq_file": as_int(row, "feature_after_file_min_gen_seq"),
        "observed_after_max_seq": as_int(row, "feature_after_max_gen_seq"),
        "may_swap": swappiness > 0,
        "may_writepage": as_bool_from_int(row, "feature_may_writepage", True),
        "may_unmap": as_bool_from_int(row, "feature_may_unmap", True),
        "avg_refaulted_anon": as_int(row, "feature_avg_refaulted_anon"),
        "avg_refaulted_file": as_int(row, "feature_avg_refaulted_file"),
        "avg_total_anon": as_int(row, "feature_avg_total_anon"),
        "avg_total_file": as_int(row, "feature_avg_total_file"),
        "protected_anon_pages": as_int(row, "feature_protected_anon_pages"),
        "protected_file_pages": as_int(row, "feature_protected_file_pages"),
        "evicted_anon_pages": as_int(row, "feature_evicted_anon_pages"),
        "evicted_file_pages": as_int(row, "feature_evicted_file_pages"),
        "refaulted_anon_pages": as_int(row, "feature_refaulted_anon_pages"),
        "refaulted_file_pages": as_int(row, "feature_refaulted_file_pages"),
        "avg_refaulted_anon_tiers": [as_int(row, f"feature_avg_refaulted_anon_tier{i}") for i in range(4)],
        "avg_refaulted_file_tiers": [as_int(row, f"feature_avg_refaulted_file_tier{i}") for i in range(4)],
        "avg_total_anon_tiers": [as_int(row, f"feature_avg_total_anon_tier{i}") for i in range(4)],
        "avg_total_file_tiers": [as_int(row, f"feature_avg_total_file_tier{i}") for i in range(4)],
        "protected_anon_tiers": [as_int(row, f"feature_protected_anon_tier{i}") for i in range(3)],
        "protected_file_tiers": [as_int(row, f"feature_protected_file_tier{i}") for i in range(3)],
        "evicted_anon_tiers": [as_int(row, f"feature_evicted_anon_tier{i}") for i in range(4)],
        "evicted_file_tiers": [as_int(row, f"feature_evicted_file_tier{i}") for i in range(4)],
        "refaulted_anon_tiers": [as_int(row, f"feature_refaulted_anon_tier{i}") for i in range(4)],
        "refaulted_file_tiers": [as_int(row, f"feature_refaulted_file_tier{i}") for i in range(4)],
        "min_nr_gens": 2,
        "max_swappiness": 200,
    }


def iter_rows(csv_path: Path) -> Iterable[Tuple[int, Dict[str, str]]]:
    with csv_path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for idx, row in enumerate(reader, start=2):
            yield idx, row


def trigger_comm_matches(row: Dict[str, str], trigger_comm: str) -> bool:
    if trigger_comm.lower() == "all":
        return True
    return row.get("trigger_comm") == trigger_comm


def page_relative_error(predicted: int, actual: int) -> float | None:
    if actual == 0:
        return None
    return abs(predicted - actual) / actual


def page_match(predicted: int, actual: int, relative_tolerance: float, zero_abs_tolerance: int) -> bool:
    if actual == 0:
        return abs(predicted) <= zero_abs_tolerance
    return abs(predicted - actual) <= max(zero_abs_tolerance, actual * relative_tolerance)


def choose_representative_case(rows: List[Tuple[int, Dict[str, str]]]) -> Tuple[int, Dict[str, str]]:
    candidates: List[Tuple[Tuple[int, int, int], int, Dict[str, str]]] = []
    for line_no, row in rows:
        anon = as_int(row, "target_reclaimed_anon_pages")
        file = as_int(row, "target_reclaimed_file_pages")
        if anon <= 0 or file <= 0:
            continue
        score = (min(anon, file), anon + file, as_int(row, "feature_evict_folios_calls"))
        candidates.append((score, line_no, row))
    if not candidates:
        raise ValueError("no filtered row with both anon/file reclaim > 0 found")
    candidates.sort(reverse=True)
    _, line_no, row = candidates[0]
    return line_no, row


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def safe_mean(values: List[int]) -> float:
    if not values:
        return 0.0
    return sum(values) / len(values)


def main() -> int:
    args = parse_args()
    csv_path = Path(args.csv).resolve()
    case_out = Path(args.case_out).resolve()
    batch_dir = Path(args.batch_dir).resolve()
    results_csv = Path(args.results_csv).resolve()
    summary_json = Path(args.summary_json).resolve()
    top_errors_json = Path(args.top_errors_json).resolve()
    config = ExecutorConfig(
        max_evict_rounds=args.max_evict_rounds,
        min_isolate_pages=args.min_isolate_pages,
    )

    filtered_rows = [
        (line_no, row)
        for line_no, row in iter_rows(csv_path)
        if trigger_comm_matches(row, args.trigger_comm)
    ]
    if not filtered_rows:
        raise SystemExit(f"no rows found in csv for trigger_comm={args.trigger_comm!r}")

    ensure_dir(batch_dir)

    picked_line_no, picked_row = choose_representative_case(filtered_rows)
    picked_case = build_case_json(picked_row)
    case_out.write_text(json.dumps(picked_case, indent=2, ensure_ascii=False), encoding="utf-8")

    result_rows: List[Dict[str, Any]] = []
    exact_both = 0
    tolerant_both = 0
    anon_exact = 0
    file_exact = 0
    anon_tolerant = 0
    file_tolerant = 0
    anon_range_hit = 0
    file_range_hit = 0
    combined_range_hit = 0
    anon_abs_errors: List[int] = []
    file_abs_errors: List[int] = []
    anon_signed_errors: List[int] = []
    file_signed_errors: List[int] = []
    anon_over = 0
    anon_under = 0
    file_over = 0
    file_under = 0

    for sample_idx, (line_no, row) in enumerate(filtered_rows, start=1):
        case_json = build_case_json(row)
        case_path = batch_dir / f"case_line_{line_no}.json"
        case_path.write_text(json.dumps(case_json, indent=2, ensure_ascii=False), encoding="utf-8")

        result = exec_shrink_lruvec(load_case(case_json), config)
        predicted_anon = int(result["analysis"]["replayed_anon_pages"])
        predicted_file = int(result["analysis"]["replayed_file_pages"])
        actual_anon = as_int(row, "target_reclaimed_anon_pages")
        actual_file = as_int(row, "target_reclaimed_file_pages")
        anon_signed_error = predicted_anon - actual_anon
        file_signed_error = predicted_file - actual_file

        anon_exact_match = predicted_anon == actual_anon
        file_exact_match = predicted_file == actual_file
        anon_tol_match = page_match(predicted_anon, actual_anon, args.relative_tolerance, args.zero_abs_tolerance)
        file_tol_match = page_match(predicted_file, actual_file, args.relative_tolerance, args.zero_abs_tolerance)
        predicted_anon_range = to_range_label(predicted_anon)
        predicted_file_range = to_range_label(predicted_file)
        actual_anon_range = to_range_label(actual_anon)
        actual_file_range = to_range_label(actual_file)
        anon_range_match = predicted_anon_range == actual_anon_range
        file_range_match = predicted_file_range == actual_file_range

        anon_exact += int(anon_exact_match)
        file_exact += int(file_exact_match)
        anon_tolerant += int(anon_tol_match)
        file_tolerant += int(file_tol_match)
        exact_both += int(anon_exact_match and file_exact_match)
        tolerant_both += int(anon_tol_match and file_tol_match)
        anon_range_hit += int(anon_range_match)
        file_range_hit += int(file_range_match)
        combined_range_hit += int(anon_range_match and file_range_match)
        anon_abs_errors.append(abs(predicted_anon - actual_anon))
        file_abs_errors.append(abs(predicted_file - actual_file))
        anon_signed_errors.append(anon_signed_error)
        file_signed_errors.append(file_signed_error)
        anon_over += int(anon_signed_error > 0)
        anon_under += int(anon_signed_error < 0)
        file_over += int(file_signed_error > 0)
        file_under += int(file_signed_error < 0)

        result_rows.append(
            {
                "sample_idx": sample_idx,
                "csv_line_no": line_no,
                "case_path": str(case_path),
                "memcg_id": as_int(row, "memcg_id"),
                "trigger_tgid": as_int(row, "trigger_tgid"),
                "trigger_tid": as_int(row, "trigger_tid"),
                "swappiness": as_int(row, "feature_swappiness"),
                "nr_to_reclaim": as_int(row, "feature_nr_to_reclaim"),
                "predicted_anon_pages": predicted_anon,
                "actual_anon_pages": actual_anon,
                "anon_abs_error": abs(anon_signed_error),
                "anon_signed_error": anon_signed_error,
                "anon_rel_error": page_relative_error(predicted_anon, actual_anon),
                "anon_exact_match": int(anon_exact_match),
                "anon_tolerant_match": int(anon_tol_match),
                "predicted_file_pages": predicted_file,
                "actual_file_pages": actual_file,
                "file_abs_error": abs(file_signed_error),
                "file_signed_error": file_signed_error,
                "file_rel_error": page_relative_error(predicted_file, actual_file),
                "file_exact_match": int(file_exact_match),
                "file_tolerant_match": int(file_tol_match),
                "predicted_anon_range": predicted_anon_range,
                "actual_anon_range": actual_anon_range,
                "anon_range_match": int(anon_range_match),
                "predicted_file_range": predicted_file_range,
                "actual_file_range": actual_file_range,
                "file_range_match": int(file_range_match),
                "combined_exact_match": int(anon_exact_match and file_exact_match),
                "combined_tolerant_match": int(anon_tol_match and file_tol_match),
                "combined_range_match": int(anon_range_match and file_range_match),
                "combined_abs_error": abs(anon_signed_error) + abs(file_signed_error),
            }
        )

    fieldnames = list(result_rows[0].keys())
    with results_csv.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(result_rows)

    total = len(result_rows)
    picked_result = next(item for item in result_rows if item["csv_line_no"] == picked_line_no)
    top_error_rows = sorted(
        result_rows,
        key=lambda item: (
            int(item["combined_abs_error"]),
            int(item["file_abs_error"]),
            int(item["anon_abs_error"]),
        ),
        reverse=True,
    )[: max(args.top_k, 0)]
    summary = {
        "csv_path": str(csv_path),
        "case_out": str(case_out),
        "batch_dir": str(batch_dir),
        "results_csv": str(results_csv),
        "top_errors_json": str(top_errors_json),
        "trigger_comm_filter": args.trigger_comm,
        "total_filtered_cases": total,
        "representative_case": {
            "csv_line_no": picked_line_no,
            "case_path": str(case_out),
            "target_reclaimed_anon_pages": as_int(picked_row, "target_reclaimed_anon_pages"),
            "target_reclaimed_file_pages": as_int(picked_row, "target_reclaimed_file_pages"),
            "predicted_anon_pages": picked_result["predicted_anon_pages"],
            "predicted_file_pages": picked_result["predicted_file_pages"],
        },
        "metrics": {
            "anon_exact_match_rate": anon_exact / total,
            "file_exact_match_rate": file_exact / total,
            "combined_exact_match_rate": exact_both / total,
            "anon_tolerant_match_rate": anon_tolerant / total,
            "file_tolerant_match_rate": file_tolerant / total,
            "combined_tolerant_match_rate": tolerant_both / total,
            "anon_range_hit_rate": anon_range_hit / total,
            "file_range_hit_rate": file_range_hit / total,
            "combined_range_hit_rate": combined_range_hit / total,
            "anon_mae": safe_mean(anon_abs_errors),
            "file_mae": safe_mean(file_abs_errors),
            "anon_mean_signed_error": safe_mean(anon_signed_errors),
            "file_mean_signed_error": safe_mean(file_signed_errors),
            "anon_overpredict_rate": anon_over / total,
            "anon_underpredict_rate": anon_under / total,
            "file_overpredict_rate": file_over / total,
            "file_underpredict_rate": file_under / total,
        },
        "tolerance": {
            "relative_tolerance": args.relative_tolerance,
            "zero_abs_tolerance": args.zero_abs_tolerance,
        },
    }
    if not args.no_top_errors_in_summary:
        summary["top_error_cases"] = top_error_rows
    summary_json.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    if not args.no_top_errors_json:
        top_errors_json.write_text(json.dumps(top_error_rows, indent=2, ensure_ascii=False), encoding="utf-8")

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
